### ISSUE TITLE
Doesn't recognize "utf8"

### ISSUE THREAD

**Issue by forivall** [iarna/has-unicode#2]
For some reason (I think it's gnome's fault), my system's locale is `en_US.utf8`. The following regex should detect both `utf8` and `UTF-8`: `/\butf-?8\b/i` (found when grepping my system trying to figure out where it's set; it's part of an old perl module).

The following line in gnome shows both `UTF-8` and `utf8` (more strictly) being accepted: https://github.com/GNOME/gnome-desktop/blob/0e2f15588a89230e60a7dfe9f4164a8c17baa733/libgnome-desktop/gnome-languages.c#L91

**Comment by gagern** [comment]
And I think you should use the same regex for `LC_CTYPE`. It follows the same syntax as the other facets, so it does include the language.

**Comment by kaylynb** [comment]
I have the same issue here. Arch Linux seems to use the lowercase variant of the locale. Have not been able to track down why (looks like [Gentoo](https://wiki.gentoo.org/wiki/Localization/Guide) does the same thing).

[`localectl` man pages](https://www.freedesktop.org/software/systemd/man/localectl.html) even reference the `.utf8` variant so I think it may be a valid.

**Comment by iarna** [comment]
This should be fixed as of 2.0.1.
